export const users = [
  {
    id: 1,
    user_id: "U001",
    username: "johndoe",
    name: "John Doe",
    business_email: "john@company.com",
    referral: "Website",
    poc: "Jane Smith",
    poc_email_address: "jane@company.com",
    first_email_status: "scheduled",
    first_email_date: "2023-05-01",
    first_email_time: "09:00:00",
    email_opened: true,
    email_open_date: "2023-05-01",
    email_open_time: "10:30:00",
    calendly_link_clicked: true,
    calendly_click_date: "2023-05-01",
    calendly_click_time: "11:15:00",
    onboarding_link_clicked: true,
    onboarding_click_date: "2023-05-02",
    onboarding_click_time: "14:00:00",
    replied: true,
    follow_up_1_status: "Not Needed",
    follow_up_1_date: null,
    follow_up_1_time: null,
    follow_up_2_status: "Not Needed",
    follow_up_2_date: null,
    follow_up_2_time: null,
    video_call_status: "Completed",
    video_call_date: "2023-05-03",
    onboarding_status: "Completed",
    onboarding_date: "2023-05-04",
    notes: "Smooth onboarding process",
    hotjar_otter_links: "https://hotjar.com/user/johndoe",
    created_at: "2023-05-01T08:00:00Z",
    updated_at: "2023-05-04T16:00:00Z",
  },
  {
    id: 2,
    user_id: "U002",
    username: "janesmith",
    name: "Jane Smith",
    business_email: "jane@othercompany.com",
    referral: "LinkedIn",
    poc: "Bob Johnson",
    poc_email_address: "bob@othercompany.com",
    first_email_status: "yet_to_schedule",
    first_email_date: "2023-05-05",
    first_email_time: "10:00:00",
    email_opened: true,
    email_open_date: "2023-05-05",
    email_open_time: "11:30:00",
    calendly_link_clicked: true,
    calendly_click_date: "2023-05-05",
    calendly_click_time: "12:15:00",
    onboarding_link_clicked: false,
    onboarding_click_date: null,
    onboarding_click_time: null,
    replied: true,
    follow_up_1_status: "Sent",
    follow_up_1_date: "2023-05-12",
    follow_up_1_time: "14:00:00",
    follow_up_2_status: "Not Needed",
    follow_up_2_date: null,
    follow_up_2_time: null,
    video_call_status: "Scheduled",
    video_call_date: "2023-05-15",
    onboarding_status: "In Progress",
    onboarding_date: "2023-05-16",
    notes: "Needs follow-up",
    hotjar_otter_links: "https://hotjar.com/user/janesmith",
    created_at: "2023-05-05T09:00:00Z",
    updated_at: "2023-05-16T17:00:00Z",
  },
  {
    id: 3,
    user_id: "U003",
    username: "alicewilliams",
    name: "Alice Williams",
    business_email: "alice@thirdcompany.com",
    referral: "Conference",
    poc: "Charlie Brown",
    poc_email_address: "charlie@thirdcompany.com",
    first_email_status: "sent",
    first_email_date: "2023-05-10",
    first_email_time: "11:00:00",
    email_opened: false,
    email_open_date: null,
    email_open_time: null,
    calendly_link_clicked: false,
    calendly_click_date: null,
    calendly_click_time: null,
    onboarding_link_clicked: false,
    onboarding_click_date: null,
    onboarding_click_time: null,
    replied: false,
    follow_up_1_status: "Sent",
    follow_up_1_date: "2023-05-17",
    follow_up_1_time: "15:00:00",
    follow_up_2_status: "Scheduled",
    follow_up_2_date: "2023-05-24",
    follow_up_2_time: "16:00:00",
    video_call_status: "Not Scheduled",
    video_call_date: null,
    onboarding_status: "Not Started",
    onboarding_date: null,
    notes: "Needs multiple follow-ups",
    hotjar_otter_links: "https://hotjar.com/user/alicewilliams",
    created_at: "2023-05-10T10:00:00Z",
    updated_at: "2023-05-24T17:00:00Z",
  },
  {
    id: 4,
    user_id: "U004",
    username: "bobjohnson",
    name: "Bob Johnson",
    business_email: "bob@fourthcompany.com",
    referral: "Referral",
    poc: "David Lee",
    poc_email_address: "david@fourthcompany.com",
    first_email_status: "yet_to_schedule",
    first_email_date: "2023-05-15",
    first_email_time: "12:00:00",
    email_opened: true,
    email_open_date: "2023-05-15",
    email_open_time: "13:30:00",
    calendly_link_clicked: true,
    calendly_click_date: "2023-05-15",
    calendly_click_time: "14:15:00",
    onboarding_link_clicked: true,
    onboarding_click_date: "2023-05-16",
    onboarding_click_time: "10:00:00",
    replied: true,
    follow_up_1_status: "Not Needed",
    follow_up_1_date: null,
    follow_up_1_time: null,
    follow_up_2_status: "Not Needed",
    follow_up_2_date: null,
    follow_up_2_time: null,
    video_call_status: "Completed",
    video_call_date: "2023-05-17",
    onboarding_status: "Completed",
    onboarding_date: "2023-05-18",
    notes: "Fast onboarding",
    hotjar_otter_links: "https://hotjar.com/user/bobjohnson",
    created_at: "2023-05-15T11:00:00Z",
    updated_at: "2023-05-18T11:00:00Z",
  },
  {
    id: 5,
    user_id: "U005",
    username: "evagarcia",
    name: "Eva Garcia",
    business_email: "eva@fifthcompany.com",
    referral: "Social Media",
    poc: "Frank White",
    poc_email_address: "frank@fifthcompany.com",
    first_email_status: "scheduled",
    first_email_date: "2023-05-20",
    first_email_time: "13:00:00",
    email_opened: true,
    email_open_date: "2023-05-20",
    email_open_time: "14:30:00",
    calendly_link_clicked: false,
    calendly_click_date: null,
    calendly_click_time: null,
    onboarding_link_clicked: true,
    onboarding_click_date: "2023-05-21",
    onboarding_click_time: "11:00:00",
    replied: true,
    follow_up_1_status: "Sent",
    follow_up_1_date: "2023-05-27",
    follow_up_1_time: "16:00:00",
    follow_up_2_status: "Not Needed",
    follow_up_2_date: null,
    follow_up_2_time: null,
    video_call_status: "Scheduled",
    video_call_date: "2023-05-28",
    onboarding_status: "In Progress",
    onboarding_date: "2023-05-29",
    notes: "Needs reminder for video call",
    hotjar_otter_links: "https://hotjar.com/user/evagarcia",
    created_at: "2023-05-20T12:00:00Z",
    updated_at: "2023-05-29T12:00:00Z",
  },
]

export const approvedUsers = [
  {
    id: "AU001",
    username: "john_doe",
    email: "john@example.com",
    instagram_username: "john_doe_11",
    followers: 1500000, // 1.5M
    campaign: "gold",
  },
  {
    id: "AU002",
    username: "jane_smith",
    email: "jane@example.com",
    instagram_username: "jane_smith_22",
    followers: 750000, // 750K
    campaign: "silver",
  },
  {
    id: "AU003",
    username: "alice_johnson",
    email: "alice@example.com",
    instagram_username: "alice_johnson",
    followers: 85000, // 85K
    campaign: "bronze",
  },
  {
    id: "AU004",
    username: "bob_williams",
    email: "bob@example.com",
    instagram_username: "bob_williams",
    followers: 25000, // 25K
    campaign: "micro",
  },
  {
    id: "AU005",
    username: "eva_brown",
    email: "eva@example.com",
    instagram_username: "eva_brown",
    campaign: "premium_influencer",
    followers: 5000,
  },
  {
    id: "AU006",
    username: "michael_davis",
    email: "michael@example.com",
    instagram_username: "michael_davis",
    campaign: "growth_campaign",
    followers: 10000,
  },
  {
    id: "AU007",
    username: "sarah_miller",
    email: "sarah@example.com",
    instagram_username: "sarah_miller",
    campaign: "premium_influencer",
    followers: 15000,
  },
  {
    id: "AU008",
    username: "david_wilson",
    email: "david@example.com",
    instagram_username: "david_wilson",
    campaign: "growth_campaign",
    followers: 20000,
  },
  {
    id: "AU009",
    username: "emily_taylor",
    email: "emily@example.com",
    instagram_username: "emily_taylor",
    campaign: "premium_influencer",
    followers: 25000,
  },
  {
    id: "AU010",
    username: "chris_anderson",
    email: "chris@example.com",
    instagram_username: "chris_anderson",
    campaign: "growth_campaign",
    followers: 30000,
  },
  {
    id: "AU011",
    username: "olivia_thomas",
    email: "olivia@example.com",
    instagram_username: "olivia_thomas",
    campaign: "premium_influencer",
    followers: 35000,
  },
  {
    id: "AU012",
    username: "daniel_jackson",
    email: "daniel@example.com",
    instagram_username: "daniel_jackson",
    campaign: "growth_campaign",
    followers: 40000,
  },
  {
    id: "AU013",
    username: "sophia_white",
    email: "sophia@example.com",
    instagram_username: "sophia_white",
    campaign: "premium_influencer",
    followers: 45000,
  },
  {
    id: "AU014",
    username: "matthew_harris",
    email: "matthew@example.com",
    instagram_username: "matthew_harris",
    campaign: "growth_campaign",
    followers: 50000,
  },
  {
    id: "AU015",
    username: "ava_martin",
    email: "ava@example.com",
    instagram_username: "ava_martin",
    campaign: "premium_influencer",
    followers: 55000,
  },
  // Add more approved users as needed
]

export const hourlyStats = [
  {
    hour: "00:00",
    emailsSent: 5,
    emailsOpened: 2,
    replies: 1,
    calendlyClicked: 1,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 1,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "01:00",
    emailsSent: 3,
    emailsOpened: 1,
    replies: 0,
    calendlyClicked: 0,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 0,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "02:00",
    emailsSent: 2,
    emailsOpened: 1,
    replies: 0,
    calendlyClicked: 0,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 0,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "03:00",
    emailsSent: 1,
    emailsOpened: 0,
    replies: 0,
    calendlyClicked: 0,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 0,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "04:00",
    emailsSent: 2,
    emailsOpened: 1,
    replies: 0,
    calendlyClicked: 0,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 0,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "05:00",
    emailsSent: 4,
    emailsOpened: 2,
    replies: 1,
    calendlyClicked: 0,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 0,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "06:00",
    emailsSent: 8,
    emailsOpened: 4,
    replies: 2,
    calendlyClicked: 1,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 1,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "07:00",
    emailsSent: 15,
    emailsOpened: 8,
    replies: 4,
    calendlyClicked: 3,
    videoCallsScheduled: 2,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 2,
    onboardingStarted: 1,
    onboarded: 0,
    unsubscribed: 1,
  },
  {
    hour: "08:00",
    emailsSent: 25,
    emailsOpened: 18,
    replies: 10,
    calendlyClicked: 8,
    videoCallsScheduled: 6,
    videoCallsCompleted: 2,
    onboardingLinkClicked: 7,
    onboardingStarted: 5,
    onboarded: 2,
    unsubscribed: 1,
  },
  {
    hour: "09:00",
    emailsSent: 35,
    emailsOpened: 28,
    replies: 15,
    calendlyClicked: 12,
    videoCallsScheduled: 10,
    videoCallsCompleted: 8,
    onboardingLinkClicked: 11,
    onboardingStarted: 9,
    onboarded: 7,
    unsubscribed: 2,
  },
  {
    hour: "10:00",
    emailsSent: 40,
    emailsOpened: 32,
    replies: 18,
    calendlyClicked: 15,
    videoCallsScheduled: 12,
    videoCallsCompleted: 10,
    onboardingLinkClicked: 14,
    onboardingStarted: 12,
    onboarded: 10,
    unsubscribed: 2,
  },
  {
    hour: "11:00",
    emailsSent: 45,
    emailsOpened: 36,
    replies: 20,
    calendlyClicked: 18,
    videoCallsScheduled: 15,
    videoCallsCompleted: 12,
    onboardingLinkClicked: 16,
    onboardingStarted: 14,
    onboarded: 12,
    unsubscribed: 3,
  },
  {
    hour: "12:00",
    emailsSent: 50,
    emailsOpened: 40,
    replies: 22,
    calendlyClicked: 20,
    videoCallsScheduled: 18,
    videoCallsCompleted: 15,
    onboardingLinkClicked: 18,
    onboardingStarted: 16,
    onboarded: 14,
    unsubscribed: 3,
  },
  {
    hour: "13:00",
    emailsSent: 48,
    emailsOpened: 38,
    replies: 21,
    calendlyClicked: 19,
    videoCallsScheduled: 16,
    videoCallsCompleted: 14,
    onboardingLinkClicked: 17,
    onboardingStarted: 15,
    onboarded: 13,
    unsubscribed: 3,
  },
  {
    hour: "14:00",
    emailsSent: 45,
    emailsOpened: 36,
    replies: 20,
    calendlyClicked: 18,
    videoCallsScheduled: 15,
    videoCallsCompleted: 12,
    onboardingLinkClicked: 16,
    onboardingStarted: 14,
    onboarded: 12,
    unsubscribed: 2,
  },
  {
    hour: "15:00",
    emailsSent: 42,
    emailsOpened: 34,
    replies: 19,
    calendlyClicked: 16,
    videoCallsScheduled: 14,
    videoCallsCompleted: 11,
    onboardingLinkClicked: 15,
    onboardingStarted: 13,
    onboarded: 11,
    unsubscribed: 2,
  },
  {
    hour: "16:00",
    emailsSent: 38,
    emailsOpened: 30,
    replies: 16,
    calendlyClicked: 14,
    videoCallsScheduled: 12,
    videoCallsCompleted: 10,
    onboardingLinkClicked: 13,
    onboardingStarted: 11,
    onboarded: 9,
    unsubscribed: 2,
  },
  {
    hour: "17:00",
    emailsSent: 35,
    emailsOpened: 28,
    replies: 15,
    calendlyClicked: 12,
    videoCallsScheduled: 10,
    videoCallsCompleted: 8,
    onboardingLinkClicked: 11,
    onboardingStarted: 9,
    onboarded: 7,
    unsubscribed: 1,
  },
  {
    hour: "18:00",
    emailsSent: 30,
    emailsOpened: 24,
    replies: 12,
    calendlyClicked: 10,
    videoCallsScheduled: 8,
    videoCallsCompleted: 6,
    onboardingLinkClicked: 9,
    onboardingStarted: 7,
    onboarded: 5,
    unsubscribed: 1,
  },
  {
    hour: "19:00",
    emailsSent: 25,
    emailsOpened: 20,
    replies: 10,
    calendlyClicked: 8,
    videoCallsScheduled: 6,
    videoCallsCompleted: 4,
    onboardingLinkClicked: 7,
    onboardingStarted: 5,
    onboarded: 3,
    unsubscribed: 1,
  },
  {
    hour: "20:00",
    emailsSent: 20,
    emailsOpened: 16,
    replies: 8,
    calendlyClicked: 6,
    videoCallsScheduled: 4,
    videoCallsCompleted: 2,
    onboardingLinkClicked: 5,
    onboardingStarted: 3,
    onboarded: 1,
    unsubscribed: 1,
  },
  {
    hour: "21:00",
    emailsSent: 15,
    emailsOpened: 12,
    replies: 6,
    calendlyClicked: 4,
    videoCallsScheduled: 2,
    videoCallsCompleted: 1,
    onboardingLinkClicked: 3,
    onboardingStarted: 2,
    onboarded: 1,
    unsubscribed: 0,
  },
  {
    hour: "22:00",
    emailsSent: 10,
    emailsOpened: 8,
    replies: 4,
    calendlyClicked: 2,
    videoCallsScheduled: 1,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 2,
    onboardingStarted: 1,
    onboarded: 0,
    unsubscribed: 0,
  },
  {
    hour: "23:00",
    emailsSent: 7,
    emailsOpened: 4,
    replies: 2,
    calendlyClicked: 1,
    videoCallsScheduled: 0,
    videoCallsCompleted: 0,
    onboardingLinkClicked: 1,
    onboardingStarted: 0,
    onboarded: 0,
    unsubscribed: 0,
  },
]

export const dailyStats = [
  {
    day: "Mar 01",
    emailsSent: 45,
    emailsOpened: 36,
    replies: 22,
    calendlyClicked: 18,
    videoCallsScheduled: 15,
    onboardingLinkClicked: 16,
    onboardingStarted: 14,
    onboarded: 12,
    videoCallsCompleted: 13,
    unsubscribed: 2,
  },
  {
    day: "Mar 02",
    emailsSent: 52,
    emailsOpened: 42,
    replies: 25,
    calendlyClicked: 20,
    videoCallsScheduled: 17,
    onboardingLinkClicked: 18,
    onboardingStarted: 16,
    onboarded: 14,
    videoCallsCompleted: 15,
    unsubscribed: 3,
  },
  {
    day: "Mar 03",
    emailsSent: 48,
    emailsOpened: 38,
    replies: 23,
    calendlyClicked: 19,
    videoCallsScheduled: 16,
    onboardingLinkClicked: 17,
    onboardingStarted: 15,
    onboarded: 13,
    videoCallsCompleted: 14,
    unsubscribed: 2,
  },
  {
    day: "Mar 04",
    emailsSent: 55,
    emailsOpened: 44,
    replies: 26,
    calendlyClicked: 21,
    videoCallsScheduled: 18,
    onboardingLinkClicked: 19,
    onboardingStarted: 17,
    onboarded: 15,
    videoCallsCompleted: 16,
    unsubscribed: 3,
  },
  {
    day: "Mar 05",
    emailsSent: 60,
    emailsOpened: 48,
    replies: 29,
    calendlyClicked: 24,
    videoCallsScheduled: 20,
    onboardingLinkClicked: 22,
    onboardingStarted: 19,
    onboarded: 17,
    videoCallsCompleted: 18,
    unsubscribed: 4,
  },
  {
    day: "Mar 06",
    emailsSent: 58,
    emailsOpened: 46,
    replies: 28,
    calendlyClicked: 23,
    videoCallsScheduled: 19,
    onboardingLinkClicked: 21,
    onboardingStarted: 18,
    onboarded: 16,
    videoCallsCompleted: 17,
    unsubscribed: 3,
  },
  {
    day: "Mar 07",
    emailsSent: 62,
    emailsOpened: 50,
    replies: 30,
    calendlyClicked: 25,
    videoCallsScheduled: 21,
    onboardingLinkClicked: 23,
    onboardingStarted: 20,
    onboarded: 18,
    videoCallsCompleted: 19,
    unsubscribed: 4,
  },
  {
    day: "Mar 08",
    emailsSent: 65,
    emailsOpened: 52,
    replies: 31,
    calendlyClicked: 26,
    videoCallsScheduled: 22,
    onboardingLinkClicked: 24,
    onboardingStarted: 21,
    onboarded: 19,
    videoCallsCompleted: 20,
    unsubscribed: 4,
  },
  {
    day: "Mar 09",
    emailsSent: 70,
    emailsOpened: 56,
    replies: 34,
    calendlyClicked: 28,
    videoCallsScheduled: 24,
    onboardingLinkClicked: 26,
    onboardingStarted: 23,
    onboarded: 20,
    videoCallsCompleted: 22,
    unsubscribed: 5,
  },
  {
    day: "Mar 10",
    emailsSent: 68,
    emailsOpened: 54,
    replies: 32,
    calendlyClicked: 27,
    videoCallsScheduled: 23,
    onboardingLinkClicked: 25,
    onboardingStarted: 22,
    onboarded: 19,
    videoCallsCompleted: 21,
    unsubscribed: 4,
  },
  {
    day: "Mar 11",
    emailsSent: 72,
    emailsOpened: 58,
    replies: 35,
    calendlyClicked: 29,
    videoCallsScheduled: 25,
    onboardingLinkClicked: 27,
    onboardingStarted: 24,
    onboarded: 21,
    videoCallsCompleted: 23,
    unsubscribed: 5,
  },
  {
    day: "Mar 12",
    emailsSent: 75,
    emailsOpened: 60,
    replies: 36,
    calendlyClicked: 30,
    videoCallsScheduled: 26,
    onboardingLinkClicked: 28,
    onboardingStarted: 25,
    onboarded: 22,
    videoCallsCompleted: 24,
    unsubscribed: 5,
  },
  {
    day: "Mar 13",
    emailsSent: 78,
    emailsOpened: 62,
    replies: 37,
    calendlyClicked: 31,
    videoCallsScheduled: 27,
    onboardingLinkClicked: 29,
    onboardingStarted: 26,
    onboarded: 23,
    videoCallsCompleted: 25,
    unsubscribed: 6,
  },
  {
    day: "Mar 14",
    emailsSent: 80,
    emailsOpened: 64,
    replies: 38,
    calendlyClicked: 32,
    videoCallsScheduled: 28,
    onboardingLinkClicked: 30,
    onboardingStarted: 27,
    onboarded: 24,
    videoCallsCompleted: 26,
    unsubscribed: 6,
  },
  {
    day: "Mar 15",
    emailsSent: 85,
    emailsOpened: 68,
    replies: 41,
    calendlyClicked: 34,
    videoCallsScheduled: 30,
    onboardingLinkClicked: 32,
    onboardingStarted: 29,
    onboarded: 26,
    videoCallsCompleted: 28,
    unsubscribed: 7,
  },
  {
    day: "Mar 16",
    emailsSent: 82,
    emailsOpened: 66,
    replies: 40,
    calendlyClicked: 33,
    videoCallsScheduled: 29,
    onboardingLinkClicked: 31,
    onboardingStarted: 28,
    onboarded: 25,
    videoCallsCompleted: 27,
    unsubscribed: 6,
  },
  {
    day: "Mar 17",
    emailsSent: 88,
    emailsOpened: 70,
    replies: 42,
    calendlyClicked: 35,
    videoCallsScheduled: 31,
    onboardingLinkClicked: 33,
    onboardingStarted: 30,
    onboarded: 27,
    videoCallsCompleted: 29,
    unsubscribed: 7,
  },
  {
    day: "Mar 18",
    emailsSent: 90,
    emailsOpened: 72,
    replies: 43,
    calendlyClicked: 36,
    videoCallsScheduled: 32,
    onboardingLinkClicked: 34,
    onboardingStarted: 31,
    onboarded: 28,
    videoCallsCompleted: 30,
    unsubscribed: 7,
  },
  {
    day: "Mar 19",
    emailsSent: 92,
    emailsOpened: 74,
    replies: 44,
    calendlyClicked: 37,
    videoCallsScheduled: 33,
    onboardingLinkClicked: 35,
    onboardingStarted: 32,
    onboarded: 29,
    videoCallsCompleted: 31,
    unsubscribed: 8,
  },
  {
    day: "Mar 20",
    emailsSent: 95,
    emailsOpened: 76,
    replies: 46,
    calendlyClicked: 38,
    videoCallsScheduled: 34,
    onboardingLinkClicked: 36,
    onboardingStarted: 33,
    onboarded: 30,
    videoCallsCompleted: 32,
    unsubscribed: 8,
  },
  {
    day: "Mar 21",
    emailsSent: 98,
    emailsOpened: 78,
    replies: 47,
    calendlyClicked: 39,
    videoCallsScheduled: 35,
    onboardingLinkClicked: 37,
    onboardingStarted: 34,
    onboarded: 31,
    videoCallsCompleted: 33,
    unsubscribed: 8,
  },
  {
    day: "Mar 22",
    emailsSent: 100,
    emailsOpened: 80,
    replies: 48,
    calendlyClicked: 40,
    videoCallsScheduled: 36,
    onboardingLinkClicked: 38,
    onboardingStarted: 35,
    onboarded: 32,
    videoCallsCompleted: 34,
    unsubscribed: 9,
  },
  {
    day: "Mar 23",
    emailsSent: 105,
    emailsOpened: 84,
    replies: 50,
    calendlyClicked: 42,
    videoCallsScheduled: 38,
    onboardingLinkClicked: 40,
    onboardingStarted: 37,
    onboarded: 34,
    videoCallsCompleted: 36,
    unsubscribed: 9,
  },
  {
    day: "Mar 24",
    emailsSent: 102,
    emailsOpened: 82,
    replies: 49,
    calendlyClicked: 41,
    videoCallsScheduled: 37,
    onboardingLinkClicked: 39,
    onboardingStarted: 36,
    onboarded: 33,
    videoCallsCompleted: 35,
    unsubscribed: 9,
  },
  {
    day: "Mar 25",
    emailsSent: 108,
    emailsOpened: 86,
    replies: 52,
    calendlyClicked: 43,
    videoCallsScheduled: 39,
    onboardingLinkClicked: 41,
    onboardingStarted: 38,
    onboarded: 35,
    videoCallsCompleted: 37,
    unsubscribed: 10,
  },
  {
    day: "Mar 26",
    emailsSent: 110,
    emailsOpened: 88,
    replies: 53,
    calendlyClicked: 44,
    videoCallsScheduled: 40,
    onboardingLinkClicked: 42,
    onboardingStarted: 39,
    onboarded: 36,
    videoCallsCompleted: 38,
    unsubscribed: 10,
  },
  {
    day: "Mar 27",
    emailsSent: 112,
    emailsOpened: 90,
    replies: 54,
    calendlyClicked: 45,
    videoCallsScheduled: 41,
    onboardingLinkClicked: 43,
    onboardingStarted: 40,
    onboarded: 37,
    videoCallsCompleted: 39,
    unsubscribed: 10,
  },
  {
    day: "Mar 28",
    emailsSent: 115,
    emailsOpened: 92,
    replies: 55,
    calendlyClicked: 46,
    videoCallsScheduled: 42,
    onboardingLinkClicked: 44,
    onboardingStarted: 41,
    onboarded: 38,
    videoCallsCompleted: 40,
    unsubscribed: 11,
  },
  {
    day: "Mar 29",
    emailsSent: 118,
    emailsOpened: 94,
    replies: 56,
    calendlyClicked: 47,
    videoCallsScheduled: 43,
    onboardingLinkClicked: 45,
    onboardingStarted: 42,
    onboarded: 39,
    videoCallsCompleted: 41,
    unsubscribed: 11,
  },
  {
    day: "Mar 30",
    emailsSent: 120,
    emailsOpened: 96,
    replies: 58,
    calendlyClicked: 48,
    videoCallsScheduled: 44,
    onboardingLinkClicked: 46,
    onboardingStarted: 43,
    onboarded: 40,
    videoCallsCompleted: 42,
    unsubscribed: 12,
  },
]

export const stats = {
  totalEmailsSent: 1000,
  totalEmailsOpened: 800,
  totalReplies: 600,
  totalCalendlyClicked: 500,
  totalVideoCallsScheduled: 450,
  totalVideoCallsCompleted: 400,
  totalOnboardingLinkClicked: 450,
  totalOnboardingStarted: 420,
  totalOnboarded: 380,
  totalUnsubscribed: 50,
}

export const weeklyStats = [
  {
    week: "Week 1",
    emailsSent: 200,
    emailsOpened: 160,
    replies: 120,
    calendlyClicked: 100,
    videoCallsScheduled: 90,
    onboardingLinkClicked: 80,
    onboardingStarted: 75,
    onboarded: 65,
    videoCallsCompleted: 70,
    unsubscribed: 10,
  },
  {
    week: "Week 2",
    emailsSent: 250,
    emailsOpened: 200,
    replies: 150,
    calendlyClicked: 125,
    videoCallsScheduled: 110,
    onboardingLinkClicked: 100,
    onboardingStarted: 90,
    onboarded: 85,
    videoCallsCompleted: 95,
    unsubscribed: 15,
  },
  {
    week: "Week 3",
    emailsSent: 300,
    emailsOpened: 240,
    replies: 180,
    calendlyClicked: 150,
    videoCallsScheduled: 130,
    onboardingLinkClicked: 120,
    onboardingStarted: 110,
    onboarded: 100,
    videoCallsCompleted: 110,
    unsubscribed: 20,
  },
  {
    week: "Week 4",
    emailsSent: 250,
    emailsOpened: 200,
    replies: 150,
    calendlyClicked: 125,
    videoCallsScheduled: 110,
    onboardingLinkClicked: 95,
    onboardingStarted: 90,
    onboarded: 80,
    videoCallsCompleted: 90,
    unsubscribed: 12,
  },
]

export const monthlyStats = [
  {
    month: "Jan",
    emailsSent: 800,
    emailsOpened: 640,
    replies: 480,
    calendlyClicked: 400,
    videoCallsScheduled: 350,
    onboardingLinkClicked: 320,
    onboardingStarted: 300,
    onboarded: 280,
    videoCallsCompleted: 300,
    unsubscribed: 40,
  },
  {
    month: "Feb",
    emailsSent: 1000,
    emailsOpened: 800,
    replies: 600,
    calendlyClicked: 500,
    videoCallsScheduled: 450,
    onboardingLinkClicked: 400,
    onboardingStarted: 380,
    onboarded: 350,
    videoCallsCompleted: 380,
    unsubscribed: 50,
  },
  {
    month: "Mar",
    emailsSent: 1200,
    emailsOpened: 960,
    replies: 720,
    calendlyClicked: 600,
    videoCallsScheduled: 550,
    onboardingLinkClicked: 480,
    onboardingStarted: 450,
    onboarded: 420,
    videoCallsCompleted: 450,
    unsubscribed: 60,
  },
  {
    month: "Apr",
    emailsSent: 1000,
    emailsOpened: 800,
    replies: 600,
    calendlyClicked: 500,
    videoCallsScheduled: 450,
    onboardingLinkClicked: 400,
    onboardingStarted: 380,
    onboarded: 350,
    videoCallsCompleted: 380,
    unsubscribed: 45,
  },
]

